### ISSUE TITLE
OpenCV Error: Unspecified error in imwrite_

### ISSUE THREAD

**Issue by ncoder-1** [jaybosamiya/busysteg#1]
Hi!

I was looking to try busysteg, but I get the following error running it (on your sample image):

[+] Loaded image
[+] Read data
[+] Calculated energies
[+] Found energy ordering
[+] Updated pixel values
OpenCV Error: Unspecified error (could not find a writer for the specified extension) in imwrite_, file /build/opencv/src/opencv-3.2.0/modules/imgcodecs/src/loadsave.cpp, line 531
terminate called after throwing an instance of 'cv::Exception'
  what():  /build/opencv/src/opencv-3.2.0/modules/imgcodecs/src/loadsave.cpp:531: error: (-2) could not find a writer for the specified extension in function imwrite_

**Comment by jaybosamiya** [comment]
It seems as though your OpenCV library can't figure out how to write to the file extension that you provided. Try using `out.bmp` as the output file (OpenCV guarantees that a `.bmp` extension is always supported). Personally, I use `out.png`, and I think that should also work on your system (since it was able to successfully load the PNG as input).

**Comment by ncoder-1** [comment]
Yep, that did it, thanks!

**Comment by jaybosamiya** [comment]
Now, after adding the commit https://github.com/jaybosamiya/busysteg/commit/6857c59c3a7825baf776e6539e1e5b241609d382, the program itself suggests this.

Thanks for pointing out this potential pitfall :smile:
